### ISSUE TITLE
Investigate how to do Automated testing in the doi-metadata-search repo. 

### ISSUE THREAD

**Issue by kjgarza** [crosscite/doi-metadata-search#105]
Currently, there is no testing or setup for Views in DataCite Search. 
child https://github.com/crosscite/doi-metadata-search/issues/89

**Comment by mfenner** [comment]
Very basic specs are setup here: https://github.com/crosscite/doi-metadata-search/tree/master/spec/features

**Comment by mfenner** [comment]
One challenge is that Phantom JS development has been suspended: http://phantomjs.org/.

**Comment by mfenner** [comment]
Possible solution is to limit testing to API calls made by the backend.

**Comment by kjgarza** [comment]
we can have specs for the API calls to event data in https://github.com/crosscite/doi-metadata-search/pull/96/files
