### ISSUE TITLE
Basic testing of the DOI views.

### ISSUE THREAD

**Issue by kjgarza** [crosscite/doi-metadata-search#106]
- We expect that usage counts are displayed in the DOI individual view when usage data exist in EventData for the same DOI.
- We expect that usage counts DONT display in the DOI individual view when usage data DOES NOT exist in EventData for the same DOI.  
- We expect that chart renders in the DOI individual view when usage data exist in EventData for the same DOI.
- We expect that the chart DOES NOT render in the DOI individual view when usage data DOES NOT exist in EventData for the same DOI. 
 child https://github.com/crosscite/doi-metadata-search/issues/89

**Comment by kjgarza** [comment]
we can have specs for the API calls to event data in https://github.com/crosscite/doi-metadata-search/pull/96/files

**Comment by richardhallett** [comment]
I've implemented basic coverage, see attached PR.
I've not implemented the chart tests yet as this hasn't worked.
One key thing I think is making sure there is a suitable css class on the charts to test against.

**Comment by richardhallett** [comment]
@kjgarza Can we agree a list of what the unit tests should be and what classes we'll add? I can then update the PR and merge to master, they don't have to pass until you've implemented.
Proposal:

Test | Expected CSS Class
-------- | --------
Usage view counts are empty | .metrics-views-empty
Usage view counts are not empty | .metrics-views-notempty
Usage download counts are empty | .metrics-downloads-empty
Usage download counts are not empty | .metrics-downloads-notempty
Usage view chart exists | .metrics-chart-views
Usage download chart exists | .metrics-chart-downloads

**Comment by kjgarza** [comment]
Consider the usecase that sometimes there is nothing displayed when dataset, but use your best judgement
![image (7).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5936775a17ad63001a910f29/125516c66e82c728ace21e0d46e1999b2487c3e1d8a0fd0fe64de29b234324676b5ee17e29d7e671eb1422515c5e1ffd42585f47a9ffda78a6b76962964e49bc8f3900299f7744eeaa880dbe09b0218e4a85b3bb8d48c3ee3425e299c2.png)

**Comment by mfenner** [comment]
@kjgarza can you explain why rows 3 and 4 are displayed differently?

**Comment by kjgarza** [comment]
if the user behind our user-stories is a data producer, each message conveys something different:

2. `0 views` , means : your datasets is not getting attention
3. `-- views`, means : your data center didn’t do their homework
4. *N/A*, means, there is nothing to do here

Like showing in the mockups 
https://datacite.atlassian.net/wiki/spaces/TEC/pages/531529771/Display+stats+in+DataCite+Search

I think we will discuss if there are better ways to display the messaging in the product meeting today.

**Comment by mfenner** [comment]
Again, what distinguishes 3. and 4.? The fact that the content type is a dataset seems arbitrary, and will no longer be valid if we for example include usage stats from IRUS UK. Can we merge 3 and 4?

**Comment by daslerr** [comment]
The stats people are submitting are aligned with the COUNTER code of practice for research data. Since these are specifically geared toward research datasets, the usage stats we will show will also likewise be only datasets. We're using "--" to indicate omission. It's possible for something to be there, but it's not available. In the case of things that aren't datasets, we won't have usage to display at all, so it's not even the case that something *could* be there.

**Comment by richardhallett** [comment]
PR updated, decided we don't actually need to test for the different use case of empty vs has data. Instead the tests are more interested that when they should be displayed something is and when there shouldnt (i.e. it's a dataset) then it isnt.
This can be adapted in the future.
