### ISSUE TITLE
Implement necessary changes in the usage data model or the chart library.

### ISSUE THREAD

**Issue by kjgarza** [crosscite/doi-metadata-search#108]
child https://github.com/crosscite/doi-metadata-search/issues/89

- using the d3 library, we need to look at the ember implementation. there is a data transformation from eventdata.

**Comment by kjgarza** [comment]
- [ ] chart array is provided directly fro mthe API
- [ ] we need to provide totals views and downalods in a different manner

**Comment by daslerr** [comment]
For the sake of documenting, we ultimately decided not to provide total views/downloads (i.e. totals including repeats and robots) for the sake of clarity and of being consistent with other Make Data Count partners. The method for providing totals exists if we later decide to switch it on.
