### ISSUE TITLE
Individual DOI view changes.

### ISSUE THREAD

**Issue by kjgarza** [crosscite/doi-metadata-search#110]
- Implement Icons for usage.
- Implement links to documentation and add messages & accompanying the text.

child https://github.com/crosscite/doi-metadata-search/issues/89

**Comment by kjgarza** [comment]
maybe merge with #107

**Comment by kjgarza** [comment]
- [ ] we conditined metrics for datasets only
- [ ] added change in text
- [ ] odofied icons
- [ ] added tabs for the charts

**Comment by kjgarza** [comment]
first round of feedback

- [ ] To make tab more tab-like
- [ ] To polish languages (views->counts, and remove unique and totals)
- [ ] To add over button in search results
- [ ] To links in views and Downloads to individual DOI view

**Comment by daslerr** [comment]
Can you make it so when you click the downloads count in the search results it takes you to the individual DOI view with the downloads tab selected?

**Comment by daslerr** [comment]
[ ] On chart tabs, add "What does this mean?" link to documentation - https://support.datacite.org/docs/usage-stats

**Comment by kjgarza** [comment]
fixed in 069ea7e963f759fb06b283b63432dae15368e1f4

**Comment by daslerr** [comment]
The link to the documentation is only showing on the views tab. It should show on both the views and downloads tabs.

**Comment by kjgarza** [comment]
fixed in https://github.com/crosscite/doi-metadata-search/commit/5e58ed886a0de1759e3ba5f6dd03bfa4297c8c03
