### ISSUE TITLE
Investigate and Define the best way to present the usage in the time domain. [KG & RD]

### ISSUE THREAD

**Issue by kjgarza** [crosscite/doi-metadata-search#112]
![](https://i.imgur.com/xdhXpAV.jpg)

- Should we the graph have y-axis information? 
- Should we have axis labels? 
- Should Downloads and views be plotted in the same chart (Stacked Bar)? 
- Should we have a tabbed view of the charts? 
- Same colours as Fabric or different colours?

child https://github.com/crosscite/doi-metadata-search/issues/89

**Comment by mfenner** [comment]
I suggest that the first version uses the setup of the d3 bar chart library.

**Comment by kjgarza** [comment]
we will use the d3 bar chart library for at least the firts version. we will revisted this in the future.
