### ISSUE TITLE
Define for messaging: missing data, accompanying the text, etc.

### ISSUE THREAD

**Issue by kjgarza** [crosscite/doi-metadata-search#115]
Messaging text in graph needs to be finalised before the implementation. This includes: Labels, graph accompanying text (description of total, no data, and graph axis.)

child https://github.com/crosscite/doi-metadata-search/issues/89

**Comment by kjgarza** [comment]
- [ ] Make clear that we are willing to show usage stats for all content, not just datasets, e.g. by talking about the COUNTER Code of Practice and not specifically the COUNTER Code of Practice for Research Data. Link should be to COUNTER website and not PeerJ preprint. 

related #120

**Comment by daslerr** [comment]
Text was updated to refer to COUNTER generally.
