### ISSUE TITLE
Investigate Best Icons for views and downloads.  

### ISSUE THREAD

**Issue by kjgarza** [crosscite/doi-metadata-search#116]
Currently, we are using random icons for views and downloads. Confusing icons was a concern reported to other interfaces that the MDC UX report showed.

child https://github.com/crosscite/doi-metadata-search/issues/89

**Comment by daslerr** [comment]
If we want to just stick with Font Awesome, then these: 

downloads: fas fa-download - https://fontawesome.com/icons/download?style=solid
views: far fa-eye - https://fontawesome.com/icons/eye?style=regular

If we want to branch out a little, then I think this one conveys the idea of multiple downloads without just looking like we're offering a way to download the data: 

downloads: https://thenounproject.com/search/?q=download&i=413666

**Comment by daslerr** [comment]
After a side conversation with the dev team, we'll stick with Font Awesome for simplicity and consistency.
