### ISSUE TITLE
Feedback on display of usage stats in DataCite Search

### ISSUE THREAD

**Issue by mfenner** [crosscite/doi-metadata-search#120]
* the x axis should start with the publication month (or January of the publication year if that info is not available) and end with the current month. Data for months before publication or after the current month should be excluded in the visualization and total counts.
* there should be information about whether usage for a given month was zero or the information was not reported.
* as there might be a long time span between publication date and current month, use the full width of the display area and show the explanatory text (COUNTER Code of Practice) under the chart. Use smaller font size for explanatory text.
* Consider showing views and downloads together, removing the tabbed navigation. This simplifies the user interface and shows correlations between views and downloads.
* Make clear that we are willing to show usage stats for all content, not just datasets, e.g. by talking about the COUNTER Code of Practice and not specifically the COUNTER Code of Practice for Research Data. Link should be to COUNTER website and not PeerJ preprint.
* More spacing below bar chart, as some month labels are cut off.
* Make sure bars look nice no matter for how many months there is data.

**Comment by kjgarza** [comment]
To be addressed in #115
- Make clear that we are willing to show usage stats for all content, not just datasets, e.g. by talking about the COUNTER Code of Practice and not specifically the COUNTER Code of Practice for Research Data. Link should be to COUNTER website and not PeerJ preprint.
- as there might be a long time span between publication date and current month, use the full width of the display area and show the explanatory text (COUNTER Code of Practice) under the chart. Use smaller font size for explanatory text.
- there should be information about whether usage for a given month was zero or the information was not reported.


I think this one should be considered at later stages, but not now
- Consider showing views and downloads together, removing the tabbed navigation. This simplifies the user interface and shows correlations between views and downloads.


This can be done in #125
- More spacing below bar chart, as some month labels are cut off.
- the x axis should start with the publication month (or January of the publication year if that info is not available) and end with the current month. Data for months before publication or after the current month should be excluded in the visualization and total counts.
- Make sure bars look nice no matter for how many months there is data. **This item needs further clarification**

**Comment by mfenner** [comment]
> Make sure bars look nice no matter for how many months there is data.

@kjgarza The width of the monthly bars should be fixed, and not calculated based on the number of months. Otherwise the bar chart looks weird if we have very few months.

**Comment by kjgarza** [comment]
Well, the *bar width* cannot be fixed because the *chart width* its fixed.  I guess you mean that we need to have a limit for *max bar width* to account for the cases in which there are only one or two months of data and avoiding having a *very wide bars*.  Does that works???

**Comment by mfenner** [comment]
I don't understand that argument. Why can't you have a fixed bar width?

**Comment by kjgarza** [comment]
lets discussed on the call, maybe we are talking baout different things.

**Comment by kjgarza** [comment]
this one is addressed in separated issues
