### ISSUE TITLE
Change messaging for works without usage counts

### ISSUE THREAD

**Issue by kjgarza** [crosscite/doi-metadata-search#123]
Decision: Change to a phrase, i.e. “We do not currently have usage information for this item” for all things we don’t have usage for (datasets and all things).

We might need a _mockup_ for this. It is unclear how this should look in the Search Results.

**Comment by kjgarza** [comment]
where to put the message 

![image](https://user-images.githubusercontent.com/1092861/54762982-72680080-4bf5-11e9-8aca-630742f6d3f5.png)

**Comment by daslerr** [comment]
Current placement and wording is fine, but the icon no longer needs to have the hover. After that change, this will be done. 

![Screenshot 2019-03-28 at 11.18.04.png](https://images.zenhubusercontent.com/5c8f4d67777e5f767e486776/a1fe95c8-226b-4a6c-b040-166d92fe2c99)
