### ISSUE TITLE
Add citations counts in Results list

### ISSUE THREAD

**Issue by kjgarza** [crosscite/doi-metadata-search#124]

**Comment by kjgarza** [comment]
fix https://github.com/crosscite/doi-metadata-search/commit/3ec56c1733b2fdd609ed1db8ab2f43e8ffa256ea

**Comment by mfenner** [comment]
Need to address duplicates in citation counts.

**Comment by kjgarza** [comment]
I think we need to define what a "duplicate citation" is.  There seem to be two cases under which we would have a duplicated citation:

(A) Two or more Events that are completely identical except for the ID.
(B) Two or more Events that have the same subject and object IDs.

(A) are not possible in EventData, therefore case (B) are the ones we care about. 

> Two or more Events that have the same subject and object IDs (and in reversed positions).

Another question that I think we might need to answer is whether "duplicated citations" should be removed from the citations list (in the individual DOI view)? If so, which "duplicates" take priority over others?

**Comment by kjgarza** [comment]
A first step would be to create a unique numeric id from sub_id and obj_id. We can create a numeric hash of the subj_id and obj_id and perform a *commutative* operation (sum or multiplication). That would give us a unique ID for unique combinations of obj and subj. 


Some Disadvantages: 
- We would need to limit the subj_id/obj_id length and that could lead to some collisions. But the probabilities are low. 
- We need to reindex all events. But we could make a copy of the index and write over that one, see https://www.elastic.co/blog/reindex-is-coming.  _reindex and _update_by_query are most useful for turning the data that you already have in Elasticsearch into the data that you want to be in Elasticsearch.

**Comment by mfenner** [comment]
What would a unique ID generated from subj_id and obj_id provide?

**Comment by kjgarza** [comment]
Considering that duplicated citation event is when Two or more Events that have the same subject and object IDs (and in reversed positions). The following events would be considered duplicated:

```
event1: {
	subj_id: B
	obj_id: A
	}

event2: {
	subj_id: A
	obj_id: B
	}
```
	
With an unique numeric ID like:

unId = A.hashcode + B.hashcode 

Then we could aggregate all the events by this unique numeric ID and count the group only. Therefore counting only the unique occurances. Like this:


```
	"aggs": {
		"unique_citations_count": {
			"cardinality": {
				"field": "unid_hash"
			}
		}
	}
	
```

**Comment by mfenner** [comment]
Why don't you concatenate subj_id and obj_id, without any hashing, e.g. `10.5555/abc-10.5555/def`.

**Comment by kjgarza** [comment]
that is a good way to avoid the hash, thanks i'll do that

**Comment by kjgarza** [comment]
To update the mapping we will need to do the following: https://github.com/datacite/lupo/issues/302

**Comment by daslerr** [comment]
Work to add ability to have citation counts in the results list is complete. We'll discuss de-duplication in another issue.
