### ISSUE TITLE
Modify bart chart to accommodate citations cases

### ISSUE THREAD

**Issue by kjgarza** [crosscite/doi-metadata-search#127]
- [x] data must be binned by year
- [x] All data available should be plotted independly of date.
- [x] the chart should plot citations distributed by YOP of each item.

child #90

**Comment by mfenner** [comment]
The bar chart for citations should show years, so x axis should end with the current year.

**Comment by kjgarza** [comment]
@daslerr @mfenner  I was thinking on whether we should highlight YOP on the chart or just leave it as a comment in the labels. What do you think??


![image](https://user-images.githubusercontent.com/1092861/58095496-6c7da400-7bd3-11e9-8c03-18da59535e20.png)

**Comment by daslerr** [comment]
I think it's nice to be able to quickly see the year of publication on the chart, too, so I would vote for highlighting it.

**Comment by mfenner** [comment]
I agree. But please don't use YOP, that is a COUNTER term, not a commonly used abbreviation.

**Comment by kjgarza** [comment]
Work on this one has been completed but new features have been added. We will address them in https://github.com/datacite/lupo/issues/313
