### ISSUE TITLE
Filter data outside `yop` and `current date` in the chart.

### ISSUE THREAD

**Issue by kjgarza** [crosscite/doi-metadata-search#128]
Change chart to show data from yop to current time always

and filter out any data outside those bounds

**Comment by mfenner** [comment]
Year of publication to current month.

**Comment by kjgarza** [comment]
- [ ] filter in the individual view.
- [ ] filter in the Search list results.

**Comment by kjgarza** [comment]
For obtaining list results without dataout of bounds for the Results Search we rely in aggregatation in `lagottino`. currently that looks like this:

```
"doisRelationTypes": [
      {
        "id": "https://doi.org/10.7280/d1j37z",
        "title": "https://doi.org/10.7280/d1j37z",
        "count": 60,
        "relationTypes": [
          {
            "id": "total-dataset-investigations-regular",
            "title": "total-dataset-investigations-regular",
            "sum": 118.0
          },
          {
            "id": "total-dataset-requests-regular",
            "title": "total-dataset-requests-regular",
            "sum": 47.0
          },
          {
            "id": "unique-dataset-investigations-regular",
            "title": "unique-dataset-investigations-regular",
            "sum": 104.0
          },
          {
            "id": "unique-dataset-requests-regular",
            "title": "unique-dataset-requests-regular",
            "sum": 47.0
          }
        ]
      },
      {
        "id": "https://doi.org/10.7272/q62z13fs",
        "title": "https://doi.org/10.7272/q62z13fs",
        "count": 57,
        "relationTypes": [
          {
            "id": "total-dataset-investigations-regular",
            "title": "total-dataset-investigations-regular",
            "sum": 4973.0
          },
          {
            "id": "total-dataset-requests-regular",
            "title": "total-dataset-requests-regular",
            "sum": 44507.0
          },
          {
            "id": "unique-dataset-investigations-regular",
            "title": "unique-dataset-investigations-regular",
            "sum": 573.0
          },
          {
            "id": "unique-dataset-requests-regular",
            "title": "unique-dataset-requests-regular",
            "sum": 4017.0
          }
        ]
      }

```

I think the dilema in this one is that there's no `yop` information  anywhere in the EventData Agent or the EventData query API. So filtering usage data from before `yop` there, its complicared.  Adding yop in the part of the workflow might be inneficient. So we need to consider alternatives. 

I'm going to separate this issue into 2 to work on it separately.

**Comment by kjgarza** [comment]
fixed in https://github.com/crosscite/doi-metadata-search/pull/133/commits/e5b63ddcf7e9a4b1b44bb693e8ec26e3fb61c256

**Comment by mfenner** [comment]
> I think the dilema in this one is that there's no yop information anywhere in the EventData Agent or the EventData query API. 

This is not correct. Please see how we index events: https://github.com/datacite/lagottino/blob/master/app/models/event.rb#L111. There is `datePublished` for both `subj` and `obj`.

**Comment by kjgarza** [comment]
Then in the future we shall implement this in the API.
