### ISSUE TITLE
Show bar chart over full width of display area

### ISSUE THREAD

**Issue by mfenner** [crosscite/doi-metadata-search#129]
As there might be a long time span between publication date and current month, use the full width of the display area and show the explanatory text (COUNTER Code of Practice) under the chart. Use smaller font size for explanatory text.

## DEV NOTES

* use fixed width for bars
* handle cases with very old year of publication (e.g. limiting display to last 10 years).

**Comment by kjgarza** [comment]
- [ ] use fixed width for bars
- [ ] handle cases with very old year of publication (e.g. limiting display to last 10 years).
    - [ ] Limit data  displaying to a max 10 years (120 bins/bars). Approx a minimun size bin/bar  of 7px.
    - [ ] Define also maximum size bin/bar for period with almost no data.
- [ ] Show bar chart over full width of display area
