### ISSUE TITLE
Only show specific relation types in citations

### ISSUE THREAD

**Issue by mfenner** [crosscite/doi-metadata-search#130]
For list of relation types that are included, see https://datacite.atlassian.net/wiki/spaces/TEC/pages/808124424/Citation+Stats+in+DataCite+Search+MVP

**Comment by kjgarza** [comment]
fix https://github.com/crosscite/doi-metadata-search/commit/c7e0576a15e3624b9d19fb758d517491da55ca98
fix https://github.com/crosscite/doi-metadata-search/commit/fa01b7bac9294c17c59eb2a9db21f45c4a217d99
