### ISSUE TITLE
Accomodate list of references(citations) in individual items

### ISSUE THREAD

**Issue by kjgarza** [crosscite/doi-metadata-search#136]
Open questions
- Should we ever Paginate the citation list?
  - e.g. "10.15468/dipjcr" has a list of 2,545 citations. View All would generate an unwieldy page. 
  - After how many records?
  - A suggestion is to show 50 by default and then paginate
- The list includes information about the publisher or datacenter . eg. "According to [[clientName]]   this item ......" when it come to items with datacite DOIs. This information could be found in the "include" object of the EventData query. However, it doesn;t seem to be indexed at the moment. see https://github.com/datacite/lagottino/issues/32

- Breaklist by relation type

**Comment by kjgarza** [comment]
needed to fix https://github.com/datacite/lagottino/issues/36

**Comment by kjgarza** [comment]
example for review https://search.test.datacite.org/works/10.5194/acp-15-13023-2015?page=2

**Comment by daslerr** [comment]
Ability to make lists is done. We will make a new issue about implementing the lists we need.

**Comment by kjgarza** [comment]
we will address new lists in https://github.com/datacite/lupo/issues/312
