### ISSUE TITLE
Irregular behavior for DOIs with special characters

### ISSUE THREAD

**Issue by adam3smith** [crosscite/doi-metadata-search#137]
Looking at this DOI: 10.1175/1520-0477(1996)077<0935:WOTWSM>2.0.CO;2 (similar behavior observed with other "weird" DOIs)
We observer the following behavior:
1. `https://doi.org/10.1175/1520-0477(1996)077<0935:WOTWSM>2.0.CO;2`
  resolves without issues
2. the CrossRef API returns metadata for both the regular and the URI encoded version of the DOI, i.e. `https://api.crossref.org/works/10.1175/1520-0477(1996)077<0935:WOTWSM>2.0.CO;2`
works, as does `https://api.crossref.org/works/10.1175%2F1520-0477%281996%29077%3C0935%3AWOTWSM%3E2.0.CO%3B2`
3. Content negotiation works when requesting bibtex: `curl -LH "Accept:application/x-bibtex" https://doi.org/10.1175%2F1520-0477%281996%29077%3C0935%3AWOTWSM%3E2.0.CO%3B2`
So far so good! BUT
4. Content negotiation requesting CrossRef Unixref silently fails: `curl -LH "Accept:application/vnd.crossref.unixref+xml" https://doi.org/10.1175%2F1520-0477%281996%29077%3C0935%3AWOTWSM%3E2.0.CO%3B2` returns empty.
5. As an additional clue, search.crossref.org also comes up empty: https://search.crossref.org/?q=10.1175%2F1520-0477%281996%29077%3C0935%3AWOTWSM%3E2.0.CO%3B2 

I know these are old and relatively rare DOIs, but we've already gotten the first complaint 5 days after switching Zotero's DOI import to content negotiation, so would love to get this working.

CC @zuphilip

**Comment by mfenner** [comment]
These things are called SICIs (https://en.wikipedia.org/wiki/Serial_Item_and_Contribution_Identifier) and predate DOIs. They are a pain to work with as they are not URL-friendly. I will ping our Crossref colleagues, as this is about their content negotiation and this might not be the best repo for this discussion. I mention @gbilder here just in case.

**Comment by gbilder** [comment]
Hi. Thanks. Looks like the SICI problem has been reported for search:

https://github.com/CrossRef/cr-search/issues/22

And I have opened new ticket for API/CN:

https://github.com/CrossRef/rest-api-doc/issues/454

**Comment by adam3smith** [comment]
Thanks! I subscribed to the API/CN ticket. @mfenner if you think it´s more appropriate there (as it seems), happy for you to close this one.

**Comment by mfenner** [comment]
Ok, closing this ticket.
