### ISSUE TITLE
Re-organise Homepage's navigation categories.

### ISSUE THREAD

**Issue by kjgarza** [crosscite/doi-metadata-search#138]
- [x] Regroup board page under the governance
- [x] Regroup statutes under governance. No changes are necessary for the statute page itself.

**Comment by kjgarza** [comment]
closed in favor of https://github.com/datacite/homepage/issues/26

**Comment by mfenner** [comment]
@kjgarza https://github.com/datacite/homepage/issues/26 doesn't exist...

**Comment by kjgarza** [comment]
This is in the wrong repo
