### ISSUE TITLE
Investigate whether we can group the multiple versions together in the display list

### ISSUE THREAD

**Issue by kjgarza** [crosscite/doi-metadata-search#142]
It could be the case that multiple versions of an instigator item all cite the same item. In the example below, we are looking at the record for item A. Item B (orange) asserts that it cites item A. Item C (yellow) asserts that it cites item A. Item D (red) asserts that it cites item A. Items B, C, and D are all versions of each other. 

![image](https://user-images.githubusercontent.com/1092861/60826658-a53b0200-a1ae-11e9-8e52-d76790c45155.png)

**Comment by kjgarza** [comment]
upon thinking on this I have come out with a pair of ideas. All of them require to request events with relationTypes for versions (hasVerison, isVersionOf, etc). 

Option 1. Request version events on the list of citations. On the client's side, once we obtain the list of citations, we can Make an extra call for `version events` of the dois in the list. We can use the resulting list to compare with the list of results. This way we can reduce the list of results to those that have no versions. Disadvantage: We need an extra API call on the individual doi view. 

Work required: 
- Add logic in the client.

Option 2. Request version events together with the list of citations. Make use of GraphQL to obtain the dataset's citations and their versions. Something along the lines of:

```
{
  dataset(id: "10.3886/icpsr29961.v2") {
    id
    publications(filter: "relationTypes:[citationRealtionTypesList]") {
      nodes {
        id
        publications(filter: "relationTypes:[citationVersionList]") {
          nodes {
            id
          }
        }
      }
    }
  }
}
```
Disadvantage: There is quite a bit of work to use it and we would need to redo a good part of the client if we want to get all the data in one single call.

Work required: 
- Add logic in the client.
- Add filters in Events calls in the graphQL API
- Add la graphQL client in search.



TODO:

- [ ] Define versions relationTypes that we will use.

**Comment by daslerr** [comment]
In the interest of getting a version of citations into test for evaluation, we'll suspend this investigation for now.
