### ISSUE TITLE
add summary to citations list

### ISSUE THREAD

**Issue by daslerr** [crosscite/doi-metadata-search#143]
In the individual DOI view in DataCite Search, the citations list is broken down by relation type, but when a list spans multiple pages, the breakdown can be non-obvious. We will add a summary to the top of the list showing how many of each type of relation is in the list.

**Comment by kjgarza** [comment]
Added summary citations in https://github.com/crosscite/doi-metadata-search/commit/0f3687dd30f382b54905a5e28c6e125ee45ee717
