### ISSUE TITLE
Citations Display Internal Feedback round

### ISSUE THREAD

**Issue by kjgarza** [crosscite/doi-metadata-search#146]
Examples: 
/// I need to spend some time identifying,  or creating, good examples. I'll put them here.

- Duplicated citation

https://search.test.datacite.org/works/10.21373/dexd-zb61

- Citations without Duplicate
https://search.test.datacite.org/works/10.1594/ieda/100037

- No citations
https://search.test.datacite.org/works/10.7272/q6g15xs4

- Links but no citations
https://search.test.datacite.org/works/10.24404/fk2.ucdlib_260452

- Citations in only one year
https://search.test.datacite.org/works/10.21373/o14ake

- Citations List without Metadata (mostly crossref)
https://search.test.datacite.org/works/10.21373/o14ake

https://docs.google.com/document/d/1qulWynBeGqKtPE_92B-mxH_jERJCJODrz8RkpVfoQf8/edit

**Comment by mfenner** [comment]
Feedback:

* the width of the chart for citations should not be fixed, but depend on the number of years displayed. In the current implementation bars are too far apart if the number of years displayed is low.
