### ISSUE TITLE
Citations tab displayed despite zero citations

### ISSUE THREAD

**Issue by mfenner** [crosscite/doi-metadata-search#159]
https://search.test.datacite.org/works/10.1073/pnas.1821543116:

![Bildschirmfoto 2019-12-10 um 16.50.52.png](https://images.zenhubusercontent.com/5698de08638e718c99601957/28cb77dc-77ae-4723-8503-d326a8361495)

**Comment by kjgarza** [comment]
fixed 
![image](https://user-images.githubusercontent.com/1092861/70866170-a6930680-1f66-11ea-9db1-976cfe998e33.png)
