### ISSUE TITLE
Refactor Usage and Citation Display

### ISSUE THREAD

**Issue by kjgarza** [crosscite/doi-metadata-search#164]
## Description

Refactor the Usage and Citation Display for the changes of the REST API 3.

Tasks

- [x] MF. Refactor Summary Counts and charts for DOI individual page. PR https://github.com/crosscite/doi-metadata-search/pull/163
- [x] KG. Define changes for the List of `citations`, `references` in the list component.
- [x] KG. Remove `Relations` List.
- [x] KG. Refactor List Component (Vue).
- [x] MF. Confirm events are properly indexed. https://github.com/datacite/lupo/issues/421

**Comment by kjgarza** [comment]
@mfenner the widget would need two lists (one for references and one for citations) of objects with the event and doi information, that is:

- **event.relation_type_id**
- **doi.resource_type_general**
- **doi.doi**
- **event.instigator** <- that could be the:
  -  true if the subj_id == doi of the page OR
  -  false if the subj_id != doi of the page 
- **The repository name** <- that could be the:
  -  doi.client_id if the subj_id == doi of the page OR
  -  event.source if the subj_id != doi of the page 

I guess these last two could also be computed from sourceDoi?

**Comment by mfenner** [comment]
* Why doi.resourceTypeGeneral?
* Why event.instigator?
* Why repository.name?
* what is doi.doi? The doi for the page that shows the list?

And to understand relation_type_id, you probably need to understand the direction, e.g. whether source_doi == subj_id or source_doi == obj_id.

**Comment by kjgarza** [comment]
https://blog.datacite.org/data-citation-display/
![image](https://user-images.githubusercontent.com/1092861/74962821-ef58b700-5410-11ea-80d6-329948ea024a.png)


> Why doi.resourceTypeGeneral?
We display this. it's from the citing/referenced DOI.

> Why event.instigator?
To phrase the sentence correctly.

> Why repository.name?
We display this, either as a sourceId (when not from datacite) or the client_id when from  datacite.

> what is doi.doi? The doi for the page that shows the list?
No, the citing/referenced DOI.

**Comment by mfenner** [comment]
Repository name is a tricky one, we will not get that directly from the event. I suggest you fetch that when you fetch the formatted citations.

**Comment by mfenner** [comment]
citation_events and reference_events are now passed on to gon.

**Comment by kjgarza** [comment]
@mfenner  to clarify the API behavior. can we clarify these two queries:

A)

> https://api.datacite.org/dois/**10.1126/science.aav0379**?include=citation-events
this query return event where the parameter id is always in the **targetDoi**:

```
{
  id: "9f76a1ee-7633-40b8-9b4a-4f4adce6d644",
  type: "events",
  attributes: {
    subjId: "https://doi.org/10.1371/journal.ppat.1008107",
    objId: "https://doi.org/10.1126/science.aav0379",
    sourceId: "crossref-related",
    sourceDoi: "10.1371/journal.ppat.1008107",
    targetDoi: "**10.1126/science.aav0379**",
    relationTypeId: "cites",
    sourceRelationTypeId: "references",
    targetRelationTypeId: "citations",
    total: 1,
    messageAction: "create",
    sourceToken: "4d47afa8-7e08-4bd9-b04a-29b691427330",
    license: "https://creativecommons.org/publicdomain/zero/1.0/",
    occurredAt: "2020-02-13T18:26:45.000Z",
    timestamp: "2020-02-16T09:15:05.145Z"
  },
  relationships: {
    doiForSource: {
      data: {
        id: "10.1371/journal.ppat.1008107",
        type: "doi"
      }
    },
    doiForTarget: {
      data: {
        id: "10.1126/science.aav0379",
        type: "doi"
      }
    }
  }
},

```

B)

> https://api.datacite.org/dois/**10.1126/science.aav0379**?include=**reference-events**

When we make this query, where does the parameter id (**10.1126/science.aav0379**) shows in the events: in the **targetDoi** or **sourceDoi** ?

**Comment by mfenner** [comment]
I don't understand the ** you are using in the URL. For citation-events the DOI of the citation is always the sourceDoi, for reference-events the DOI of the reference is always the targetDoi.

**Comment by kjgarza** [comment]
thanks. sorry it seems to be that markdown did work
