### ISSUE TITLE
Add download links for content negotiation

### ISSUE THREAD

**Issue by mfenner** [crosscite/doi-metadata-search#70]
As a researcher, I want to easily get the metadata for a DOI in the formats provided via content negotiation, including custom metadata registered by a data center.

#### DEV NOTES

Provide the following download links:
* DataCite XML
* [RDF/XML](https://en.wikipedia.org/wiki/RDF/XML)
* Schema.org JSON/LD
* Citeproc JSON

Plus custom MIME types registered by the data center.

**Comment by mfenner** [comment]
Should we consider mapping popular custom MIME types to file types? E.g. `chemical/x-cml` in https://search.datacite.org/works/10.14469/CH/17168 to `Chemical Markup Language` (see https://www.ch.ic.ac.uk/chemime/).

**Comment by kjgarza** [comment]
Got a CSV of that table. I need to implement the code

**Comment by kjgarza** [comment]
fixed: d1276b5

**Comment by mfenner** [comment]
Looks good.

**Comment by augustfly** [comment]
Excuse me if I mis-understand, but I am not sure as to why can I see the CN link here:

https://search.datacite.org/works/10.14469/CH/17168

and can resolve it here:

`curl -LH "Accept: chemical/x-cml" https://doi.org/10.14469/CH/17168` 

but not here

https://data.datacite.org/chemical/x-cml/10.14469/CH/17168

I'm happy to be sent back to documentation that I've overlooked or mis-read. FWIW I'm trying to advise an astronomy archive about whether or not submitting content negotiated links directly to their data is worth their effort. 

thanks

**Comment by mfenner** [comment]
@augustfly this is a bug/missing feature. Providing the content-type in the link is a workaround to make it easier to provide content negotiation. Currently this works only for the built-in content types, not the content types registered by users. One important shortcoming is that you have to use data.datacite.org instead of doi.org.

Would that be important functionality we should add?

**Comment by augustfly** [comment]
Thanks @mfenner. I'm not sure it is important functionality because of the potential weeds a data center might find itself maintaining their custom content types and links. 

I have had colleagues ( @MatthewTurk ) who have been intrigued by the potential for this kind of functionality for accessing custom content types this way. 

One place I am struggling is finding documentation on submitting and maintaining custom content types. I think I am overlooking some docs perhaps in my haste.
