### ISSUE TITLE
Metadata search and aPI pagination is not working

### ISSUE THREAD

**Issue by kjgarza** [crosscite/doi-metadata-search#72]
I have noticed that the pagination in the REST API via the offset parameter does not seem to be working: I always get the same 100 records in this example query:
 
https://api.datacite.org/works?data-center-id=bl.cam&rows=100&offset=200
 
Has anything changed? I developed a script a while ago to iterate through all Cambridge DOIs but now it does not seem to be working as before.
 
Best regards,
Agustina

**Comment by mfenner** [comment]
We have switched to using JSONAPI spec for pagination: `page[number]` and `page[size]` instead of `offset` and `rows`.  I have updated the documentation at https://support.datacite.org accordingly.

**Comment by mfenner** [comment]
Fixed DataCite Search via https://github.com/datacite/datacite/issues/245. Updated documentation to point out that we have started using `page[number]` and `page[size]` instead of `offset` and `rows`. E.g. https://api.datacite.org/works?data-center-id=bl.cam&page[size]=100&page[number]=3
