### ISSUE TITLE
Define type of usage to display

### ISSUE THREAD

**Issue by kjgarza** [crosscite/doi-metadata-search#91]
child crosscite/doi-metadata-search#89

@daslerr  I can't seem to be able to add you to the list

So far we are focusing in displaying total counts

**Comment by kjgarza** [comment]
https://datacite.atlassian.net/wiki/spaces/TEC/pages/531529771/Display+usage+and+citation+stats+in+DataCite+Search

**Comment by mfenner** [comment]
Continue discussion in wiki.
